version: 0.0
os: linux
files:
   - source: /EC2/main.py
   destination: /home/ec2-user/codes
   hooks:
   BeforeInstall: - location: scripts/install_dependencies
   timeout: 300
   runas: root - location: scripts/start_server
   timeout: 300
   runas: root
   ApplicationStop: - location: scripts/stop_server
   timeout: 300
   runas: root

